# Generated by Django 4.0.3 on 2022-03-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='seconds_resting',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='seconds_working',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
